#!/usr/bin/env python3
"""Cross-validated threshold search against the official 0.4/0.6 score.

No ASR/NLI inference happens here.  It replays decisions from the development
cache generated by dev/generate_dev_cache.py.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from dev.common import load_config, merge_config, read_json, score_records, write_csv, write_json
from dev.threshold_logic import decide_cached_record

DEFAULT_PARAMETERS = [
    "event_member_yes_floor",
    "dual_event_yes_threshold",
    "single_source_yes_threshold",
    "exact_fact_yes_threshold",
    "asr_fact_disagreement_yes_threshold",
    "generic_disagreement_yes_threshold",
    "strong_entailment_threshold",
    "event_yes_no_margin",
]


def _candidate_values(name: str, base: float) -> list[float]:
    if name == "event_yes_no_margin":
        values = [0.0, 0.02, 0.03, 0.05, 0.08, 0.12, 0.16]
    else:
        values = [
            base - 0.16,
            base - 0.12,
            base - 0.08,
            base - 0.04,
            base,
            base + 0.04,
        ]
    return sorted({round(max(0.0, min(0.95, value)), 4) for value in values})


def _score(records: list[dict[str, Any]], config: dict[str, Any]) -> dict[str, Any]:
    decisions = [decide_cached_record(record, config) for record in records]
    return score_records(records, decisions, config)


def coordinate_search(
    records: list[dict[str, Any]],
    base_config: dict[str, Any],
    parameters: list[str],
    passes: int,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    config = dict(base_config)
    history: list[dict[str, Any]] = []

    for pass_index in range(passes):
        changed = False
        for name in parameters:
            base = float(config[name])
            best_value = base
            best_metrics = _score(records, config)

            for value in _candidate_values(name, base):
                trial = dict(config)
                trial[name] = value
                metrics = _score(records, trial)
                history.append({
                    "pass": pass_index + 1,
                    "parameter": name,
                    "value": value,
                    "score": metrics["score"],
                    "accuracy": metrics["accuracy"],
                    "mean_tiou": metrics["mean_tiou"],
                    "yes_recall": metrics["yes_recall"],
                    "yes_precision": metrics["yes_precision"],
                    "fp": metrics["fp"],
                    "fn": metrics["fn"],
                })
                key = (
                    metrics["score"],
                    metrics["mean_tiou"],
                    metrics["yes_recall"],
                )
                best_key = (
                    best_metrics["score"],
                    best_metrics["mean_tiou"],
                    best_metrics["yes_recall"],
                )
                if key > best_key:
                    best_value = value
                    best_metrics = metrics

            if best_value != base:
                config[name] = best_value
                changed = True

        if not changed:
            break

    return config, history


def _folds(records: list[dict[str, Any]], k: int) -> list[set[str]]:
    conversations = sorted({str(record["transcript_id"]) for record in records})
    folds = [set() for _ in range(k)]
    for index, conversation in enumerate(conversations):
        folds[index % k].add(conversation)
    return folds


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", default="dev_cache/e1_dev_cache.json.gz")
    parser.add_argument("--config", default="config/e1_default.json")
    parser.add_argument("--output-dir", default="dev_results/threshold_search")
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--passes", type=int, default=3)
    parser.add_argument("--parameters", nargs="+", default=DEFAULT_PARAMETERS)
    parser.add_argument(
        "--write-config",
        default="config/e1_threshold_tuned.json",
        help="Write the full-data recommendation as a complete E1 config.",
    )
    args = parser.parse_args()

    cache = read_json(args.cache)
    records = list(cache["records"])
    base = load_config(args.config)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    base_metrics = _score(records, base)
    folds = _folds(records, max(2, args.folds))
    cv_rows: list[dict[str, Any]] = []
    all_history: list[dict[str, Any]] = []

    for fold_index, validation_ids in enumerate(folds, start=1):
        train = [r for r in records if str(r["transcript_id"]) not in validation_ids]
        validation = [r for r in records if str(r["transcript_id"]) in validation_ids]
        tuned, history = coordinate_search(train, base, args.parameters, args.passes)
        val_metrics = _score(validation, tuned)
        cv_rows.append({
            "fold": fold_index,
            "train_questions": len(train),
            "validation_questions": len(validation),
            "score": val_metrics["score"],
            "accuracy": val_metrics["accuracy"],
            "mean_tiou": val_metrics["mean_tiou"],
            "yes_recall": val_metrics["yes_recall"],
            "yes_precision": val_metrics["yes_precision"],
            "fp": val_metrics["fp"],
            "fn": val_metrics["fn"],
            "tuned_thresholds": json.dumps(
                {key: tuned[key] for key in args.parameters},
                sort_keys=True,
            ),
        })
        for row in history:
            row = dict(row)
            row["fold"] = fold_index
            all_history.append(row)

    full_tuned, full_history = coordinate_search(
        records,
        base,
        args.parameters,
        args.passes,
    )
    full_metrics = _score(records, full_tuned)
    for row in full_history:
        row = dict(row)
        row["fold"] = "full"
        all_history.append(row)

    cv_score = sum(row["score"] for row in cv_rows) / len(cv_rows)
    cv_accuracy = sum(row["accuracy"] for row in cv_rows) / len(cv_rows)
    cv_tiou = sum(row["mean_tiou"] for row in cv_rows) / len(cv_rows)

    summary = {
        "base_metrics_full_training_set": base_metrics,
        "cv": {
            "folds": len(cv_rows),
            "mean_score": cv_score,
            "mean_accuracy": cv_accuracy,
            "mean_tiou": cv_tiou,
        },
        "full_training_recommendation_metrics": full_metrics,
        "recommended_thresholds": {
            key: full_tuned[key]
            for key in args.parameters
        },
        "important": (
            "Use CV metrics to judge generalization. The full-data recommendation is "
            "the deployment candidate, not an unbiased estimate."
        ),
    }

    write_csv(output_dir / "cv_folds.csv", cv_rows)
    write_csv(output_dir / "search_history.csv", all_history)
    write_json(output_dir / "summary.json", summary)
    write_json(args.write_config, full_tuned)

    print(json.dumps(summary, indent=2))
    print(f"Wrote tuned config: {args.write_config}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
